apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  app.kubernetes.io/version: v0.6.0
  catalog.kubestack.com/heritage: kubestack.com/catalog/tektoncd
  catalog.kubestack.com/variant: base
commonLabels:
  app.kubernetes.io/component: controller
  app.kubernetes.io/managed-by: kubestack
  app.kubernetes.io/name: tektoncd
resources:
- release.yaml
